"""empty message

Revision ID: 5ef12c46c7d8
Revises: 6ac578264ac3
Create Date: 2024-10-03 18:55:55.344161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ef12c46c7d8'
down_revision = '6ac578264ac3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('music', schema=None) as batch_op:
        batch_op.add_column(sa.Column('album_link', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('music', schema=None) as batch_op:
        batch_op.drop_column('album_link')

    # ### end Alembic commands ###
